### ISSUE TITLE
All logging methods that use a formatter can throw exceptions!

### ISSUE THREAD

**Issue by arkasoft** [chillblox/jdk14-log#1]
All the methods that have a formatter used in them i.e. the methods with the format:

public void e(String format, Object... args) 

can potentially through a Runtime exception which means that what you are using to LOG messages can either crash your code or when your code has crashed will fail to log the error because you have the wrong formatter or error in your formatter or Null in your format string.

These methods must either throw an exception *which would then mean no one would really ever use them in practice* **or** handle all the cases so that the method would never throw a Runtime exception that could result in the code crashing or not logging an error.

For Example:

```java
public class LogTester {
  public static  Log LOG = LogFactory.get(LogTester.class);
  public static void main(String[] args) {
    try {
      throw new NullPointerException();
    } catch (Exception err) {
      System.out.println ("err.getMessage(): " +err.getMessage());
      System.out.println ("err: "+err);
      LOG.e (err.getMessage(), err);
    }

  }
}
```

**Comment by ggeorg** [comment]
for every 

`public void e(String format, Object... args) {}`

there is also a:

`public void e(Throwable t, String format, Object... args) {}`

The reason I created this wrapper is this and I mention that in the features:
* **parameterization of logging statements in presence of an exception**

those methods show the stack trace.

**Comment by arkasoft** [comment]
Yes but when the method can throw a runtime exception and someone uses it not knowing because they don't read the docs and their code fails and the log also fails they get screwed.

This happened today with logging you had added. So if you can make this mistake anyone else can too. So it makes sense to either add the exception into the method or simply deal with it in the method.

**Comment by ggeorg** [comment]
None of the current frameworks has this and I don't know why - the latest version of SLF4J added this feature but it a very bad way:

http://www.slf4j.org/faq.html#paramException

they do extra treatment of the last parameter that is not explicitly defined as an exception but just as an Object - that means they are not type-safe. The solution for a this is to change the API and put the exception before the format string like I show in my demos.

And you never log:
```
try {
...
} catch(Exception ex) {
   LOG.e(e, "Operation failed because of: %s", ex.getMessage());
}
```
because the Exception message is already included in the stack trace. So you could log like:

```
try {
...
} catch(Exception ex) {
   LOG.e(e, "Operation XXX with param1=%d, param2=%s failed", param1, param2);
}
```

where param1, and param2 could be the input parameters of the operation that throw the exception.

**Comment by ggeorg** [comment]
1.0.3 does not throw RuntimeException when format string is wrong or arguments don't match format string or a RuntimeError is thrown in Callback.

e.g. this

LOG.i("Arguments length: %d", String.valueOf(args.length));
will log

Dec 29, 2015 12:51:37 AM test.logging.Test main
WARNING: Arguments length: %d [java.util.IllegalFormatConversionException: d != java.lang.String]
